### ISSUE TITLE
Can't download heatmap as SVG

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-feature-table#141]
When I try to do this, the heatmap always opens in a new window, both in Firefox and in Chrome, just for the record:

![heatmap](https://user-images.githubusercontent.com/375307/30780578-16ac2dae-a0c3-11e7-999b-e408bf5e2e4d.gif)

**Comment by thermokarst** [comment]
Thanks for reporting @ElDeveloper! This isn't really a QIIME 2 bug, it has to do with a whole host of conditions related to browser APIs in relation to q2view, `qiime tools view`, `https://` protocol, and `file://` protocol (for a brief primer, see https://github.com/qiime2/q2view/issues/65, https://github.com/qiime2/q2-feature-table/issues/120, and https://github.com/qiime2/q2-feature-table/pull/130). At this point there really isn't anything we can do to fix it (because this relates to browser APIs that we have no control over), so I am going to close this issue. Thanks again!

**Comment by thermokarst** [comment]
Rereading I didn't make this very clear --- technically it is "Downloading" when it is opening in a new tab, at least as far as the browsers are concerned - the "download" dialog and opening in a new window/tab are effectively the same thing (I think we are all on the same page that to a user this doesn't really feel like the same thing, but such is life). Using the file dialog to save the SVG that is opening in the new window/tab still works, and is hopefully a familiar action for some/most users.

**Comment by ElDeveloper** [comment]
Fair enough, didn't know this was an issue.

> Using the file dialog to save the SVG that is opening in the new window/tab still works, and is hopefully a familiar action for some/most users.

This is not quite working for me, maybe I am missing something, both Chrome and Firefox fail in slightly different ways. In Chrome: 

![bug](https://user-images.githubusercontent.com/375307/30817764-9f4f0fda-a1ce-11e7-976b-6b5422af1d1f.gif)

In Firefox I only get the option to download the page which later fails to open, so this is how I'm saving:

![bug-firefox](https://user-images.githubusercontent.com/375307/30817885-f1739902-a1ce-11e7-9124-2e834098469f.gif)

And this is what results from that file (note Illustrator can't open that file):

![screen shot 2017-09-25 at 8 52 44 am](https://user-images.githubusercontent.com/375307/30817930-0a913782-a1cf-11e7-9db5-a43fe6d7057b.png)

**Comment by thermokarst** [comment]
Ugh - sorry dude! Can you throw this up on issue tracked at https://github.com/qiime2/q2view? Also, does it work if you use `qiime tools view`?

**Comment by ElDeveloper** [comment]
Fair enough, this works with `qiime tools view`.
