### ISSUE TITLE
Should biom.Table operations be done inplace when possible?

### ISSUE THREAD

**Issue by jakereps** [qiime2/q2-feature-table#21]
While working on `filter` with @gregcaporaso, we noticed a few methods are using `inplace=False`, which could be undesirable if the table is large enough to possibly fill the user's memory. Should methods that allow `inplace` be set to `True`?

Ping: @qiime2/core-developers

**Comment by gregcaporaso** [comment]
I think we have to do this - we're going to get bitten really quickly by having more than one copy of feature tables in memory (in QIIME 1 we had to avoid this at all cost).

**Comment by jairideout** [comment]
This would be a nice improvement, and there are no issues as far as the framework is concerned, as long as the method returns the mutated input. Input artifacts passed via the "artifact API" won't be mutated in-place either; you will always get a new output artifact without there needing to be two copies in memory!

I recommend documenting any "view API" that mutates in-place to make it clear to developers using that API directly. It might be easy to miss that detail because the "view API" will mutate in-place and also return a value, which is not how in-place mutators typically work.
